---
title: "ggplot"
output: html_document
---
#ggplot2
```{r}
library(ggplot2)
pl<-ggplot(data=mtcars,aes(x=mpg,y=hp))
pl+geom_point()

```


```{r}
#blocked by different cylinder counts
#facet_grid(cly~.)
#+ stat_smooth() #smooth line fit, error measure shown through shadow
#+ coord_cartesian(xlim=c(15,25)) #limiting coordinates

#+theme_bw() #plot size, coloring
```

#histogram
frequency of a single variable
```{r}
#install.packages("ggplot2movies")
library(ggplot2)
library(ggplot2movies)
#data asethetics
pl<-ggplot(movies,aes(x=rating))
pl+geom_histogram()

#geometry
pl2<-pl+geom_histogram(binwidth=0.1, color='red',fill='pink',alpha=0.4) #edit width of bin

pl2 + xlab("movie rating") + ylab("count") + ggtitle("histogram")


```

#scatterplots
```{r}
df<-mtcars

pl<-ggplot(df,aes(x=wt,y=mpg))
pl + geom_point()
#geometry
pl + geom_point(alpha=0.5,size=5)

pl+geom_point(aes(size=hp,alpha=0.5)) #thinks continuous

pl+ geom_point(aes(size=cyl)) #but categorical
pl+geom_point(aes(size=factor(cyl))) #still not good
pl+geom_point(aes(shape=factor(cyl),color=factor(cyl)),size = 3) #shape and color

pl + geom_point(size=5,color="#56ea29") #hex color

pl2<- pl + geom_point(aes(color=hp),size=5) #gradient

pl2 + scale_color_gradient(low="blue",high="red")
#easy to pick out outlier
```

#barplots
counts for categorical data
```{r}
df<-mpg
pl<-ggplot(df,aes(x=class))
pl + geom_bar()
pl+ geom_bar(fill="blue")
pl+ geom_bar(aes(fill=drv))#stacked vertical
pl+ geom_bar(aes(fill=drv),position="dodge") #side to side
pl+ geom_bar(aes(fill=drv),position="fill") #percentage
 
```

#boxplots
```{r}
df<-mtcars
library(ggplot2)
pl<-ggplot(df,aes(x=factor(cyl),y=mpg)) #need to factor ctegorical
pl + geom_boxplot() #need group

pl + geom_boxplot() + coord_flip()
pl + geom_boxplot(aes(fill=factor(cyl)))+theme_bw() 
```

#2 variable plotting
```{r}
library(ggplot2movies)
pl<- ggplot(movies,aes(x=year,y=rating))
pl+geom_bin2d()+ scale_fill_gradient(high="red",low="green")#almost like a heat map

pl+geom_bin2d(binwidth=c(3,1))+ scale_fill_gradient(high="red",low="green")

pl+geom_hex()
#install.packages('hexbin')

pl+geom_density2d()

```

#cooridnats and faceting
```{r}
pl<-ggplot(mpg,aes(x=displ,y=hwy))+geom_point()
#scatter

pl + coord_cartesian(xlim=c(1,4),ylim=c(15,30))
pl+ coord_fixed(ratio=1/3) #aspect ratio do not change

pl + facet_grid(.~cyl) #facet by one, on categorical
pl + facet_grid(drv~cyl) #by two dimensional facet
pl + facet_grid(drv~.)

```

#themes
```{r}
theme_set(theme_minimal())
pl<-ggplot(mtcars,aes(x=wt,y=mpg))+geom_point()

print(pl+theme_dark())
#install.packages("ggthemes")

library(ggthemes)
pl+theme_fivethirtyeight()


```

